#!/usr/bin/env python3
"""Generate (and re-assert) the README's battery-2 post-registration block.

Numbers discipline: no result number in the battery-2 paragraph may be
hand-typed.  This script derives every number it prints from the shipped
battery-2 study JSONs (pilot2/poststudy2_20260823/{s4/s4_summary.json,
s5/s5_cost_sweep.json, s6/s6_summary.json, s7/s7_summary.json} plus the
s7 per-question ledger), from the on-disk PREREG bytes (hashed, never
quoted from memory) and from the frozen main-study verdict matrix
(pilot2/pilot2_arms_summary.json), cross-checking each figure across
every JSON that states it and dying on any inconsistency.  It then
splices the paragraph between the marker comments below (directly after
the battery-1 block).

Usage:
  python3 scripts/gen_readme_poststudy2.py            # print the block
  python3 scripts/gen_readme_poststudy2.py --write    # update README.md
  python3 scripts/gen_readme_poststudy2.py --check    # assert README is
                                                      # exactly what
                                                      # --write produces
"""
import hashlib
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PS2 = os.path.join(ROOT, "pilot2", "poststudy2_20260823")
README = os.path.join(ROOT, "README.md")
BEGIN = ("<!-- POSTSTUDY2_BLOCK_BEGIN generated by "
         "scripts/gen_readme_poststudy2.py; do not hand-edit -->")
END = "<!-- POSTSTUDY2_BLOCK_END -->"
B1_END = "<!-- POSTSTUDY_BLOCK_END -->"


def die(msg):
    sys.stderr.write("gen_readme_poststudy2: FAIL: %s\n" % msg)
    sys.exit(1)


def load(rel):
    with open(os.path.join(PS2, rel), encoding="utf-8") as f:
        return json.load(f)


# ---------------------------------------------------------------- evidence
prereg = os.path.join(PS2, "PREREG_poststudy2_20260823.md")
SHA = hashlib.sha256(open(prereg, "rb").read()).hexdigest()
if len(SHA) != 64:
    die("prereg sha is not 64 hex chars")
freeze = open(os.path.join(PS2, "FREEZE_poststudy2.sha256"),
              encoding="utf-8").read()
if SHA not in freeze:
    die("FREEZE_poststudy2.sha256 does not record the on-disk PREREG sha")

S4 = load("s4/s4_summary.json")
S5 = load("s5/s5_cost_sweep.json")
S6 = load("s6/s6_summary.json")
S7 = load("s7/s7_summary.json")
S7L = load("s7/s7_ledger.json")
if not (S4["prereg_sha256"] == S5["prereg"]["sha256"]
        == S5["substrates_manifest"]["prereg_sha256"]
        == S6["prereg_sha256"] == S7["prereg_sha256"]
        == S7L["prereg_sha256"] == SHA):
    die("a battery-2 study JSON pins a different PREREG sha256")

# frozen main-study verdict matrix (ZH rep-1 anchors, recomputed) ------
ARMS = json.load(open(os.path.join(ROOT, "pilot2",
                                   "pilot2_arms_summary.json"),
                      encoding="utf-8"))
V = ARMS["per_question_verdicts"]
N = len(V)
BB, GOV = "baseline_claude", "governance_informed"


def frozen_errors(arm):
    return sum(v[arm] != "correct" for v in V.values())


ZH_B, ZH_G = frozen_errors(BB), frozen_errors(GOV)

# S4 ------------------------------------------------------------------
PD = S4["paired_differences"]
if not (S4["reference_errors"] == PD[GOV]["errors_reference"] == ZH_B
        and PD[GOV]["errors_arm"] == ZH_G
        and PD[GOV]["n_questions"] == N):
    die("S4 anchors disagree with the frozen verdict matrix")
GLO, GHI = PD[GOV]["ci95_percentile"]
if not (GLO <= 0.0 <= GHI) or PD[GOV]["ci_excludes_zero"]:
    die("S4 governance CI bookkeeping inconsistent with its bounds")
V3 = PD["trivial_v3"]
if not (V3["ci_excludes_zero"] and V3["ci95_percentile"][1] < 0):
    die("S4 trivial_v3 CI is not excluded on the harmful side")
S4V = {k: S4["predictions"][k]["verdict"] for k in ("S4-P1", "S4-P2",
                                                    "S4-P3")}
if (S4V != {"S4-P1": "MISS", "S4-P2": "MISS", "S4-P3": "MET"}
        or S4["n_predictions_missed"] != 2):
    die("S4 verdicts moved: %r" % (S4V,))
ELIM = S4["elimination_restatement"]
if not (ELIM["all_in_band"] and ELIM["range_straddles_line"]):
    die("S4-P3 elimination bookkeeping inconsistent")

# S5 ------------------------------------------------------------------
P1, P2, P3 = (S5["predictions"][k] for k in ("S5-P1", "S5-P2", "S5-P3"))
if not (P1["verdict"] == "MISS" and not P1["monotone_non_decreasing"]
        and P1["growth_at_most_linear"]):
    die("S5-P1 bookkeeping moved")
MED = P1["medians_s"]
GROWTH = MED["scale_400"] / MED["scale_100"]
if abs(GROWTH - P1["growth_100_to_400"]) > 1e-12 or GROWTH >= 4.0:
    die("S5 growth factor does not re-derive from the medians")
if not (P2["verdict"] == "MET" and P2["median_in_band_at_every_point"]
        and P2["strict_all_certificates_verdict"] == "MISS"):
    die("S5-P2 two-reading bookkeeping moved")
if not (P3["verdict"] == "MET" and P3["all_window_bounded"]
        and all(v == 0
                for v in P3["full_scan_audits_per_point"].values())):
    die("S5-P3 full-scan census is not zero everywhere")
FACTORS = sorted(p["row_factor"] for p in S5["row_scale_axis"])
if len(FACTORS) != len(MED) or any(
        not p["reachable"] for p in S5["row_scale_axis"]):
    die("row-scale axis and median table disagree, or a point unreachable")
PC = S5["provenance_correction"]
if not (PC["defect"]["correct_value"] == SHA
        and PC["defect"]["corrupted_value"] != SHA
        and len(PC["defect"]["corrupted_value"]) == 62
        and PC["impact"].startswith("metadata-only")
        and len(PC["defect"]["fields_corrected"]) == 2):
    die("S5 provenance-correction record inconsistent")

# S6 ------------------------------------------------------------------
EN_B = S6["error_counts_en"][BB]
EN_G = S6["error_counts_en"][GOV]
if not (S6["n_questions"] == N
        and S6["zh_anchors_frozen"]["error_counts"][BB] == ZH_B
        and S6["zh_anchors_frozen"]["error_counts"][GOV] == ZH_G):
    die("S6 ZH anchors disagree with the frozen verdict matrix")
if not (abs(EN_B - ZH_B) == 1 and abs(EN_G - ZH_G) == 1 and EN_B > EN_G):
    die("S6 one-question movement / EN ordering broke")
PR7 = S6["probe7"]
if not (len(PR7["qids"]) == 7
        and PR7["en_governance_errors"]
        == sum(v != "correct"
               for v in PR7["en_governance_verdicts"].values())
        and PR7["en_governance_errors"] > 7 // 2):
    die("S6 probe-7 concentration bookkeeping broke")
if not all(S6["predictions"][p]["met"]
           for p in ("S6-P1", "S6-P2", "S6-P3", "S6-P4")):
    die("an S6 prediction is not met")

# S7 ------------------------------------------------------------------
E2E = S7["end_to_end_error"]
SIG = S7["exact_full_sigma"]
LED = S7L["ledger"]
if not (S7["n"] == N and E2E + S7["end_to_end_correct"] == N
        and sum(r["verdict"] == "error" for r in LED) == E2E
        and sum(bool(r["exact_full_sigma"]) for r in LED) == SIG
        and len(LED) == N):
    die("S7 ledger recount disagrees with the summary")
if S7["exact_sigma_and_wrong"] != []:
    die("an exact-sigma question errs end-to-end")
if not (S7["reference_points"]["governance_informed_error_frozen"] == ZH_G
        and S7["reference_points"]["backbone_error_frozen"] == ZH_B):
    die("S7 reference points disagree with the frozen verdict matrix")
if not all(S7["predictions"][p]["met"]
           for p in ("S7-P1", "S7-P2", "S7-P3", "S7-P4")):
    die("an S7 prediction is not met")

# derived miss roster --------------------------------------------------
MISSES = [k for k, v in S4V.items() if v == "MISS"]
MISSES += [k for k in ("S5-P1",) if S5["predictions"][k]["verdict"]
           == "MISS"]
if len(MISSES) != 3:
    die("miss roster is not the three recorded misses: %r" % (MISSES,))

# ---------------------------------------------------------------- block
PSD = "pilot2/poststudy2_20260823"
BLOCK = f"""{BEGIN}
### Post-registration studies, battery 2 (2026-08-23)

A second pre-registered battery hardens four more threat sentences ---
uncertainty on the paired headline contrast, cost-model scalability,
the cross-lingual protocol, and the input modality. All four studies
were pre-registered in
[`{PSD}/PREREG_poststudy2_20260823.md`]({PSD}/PREREG_poststudy2_20260823.md)
(sha256 `{SHA}`,
frozen before any study ran and re-asserted from the on-disk bytes by
`FREEZE_poststudy2.sha256`, by every study JSON and by the number gate),
misses published as misses --- {len(MISSES)} occurred
({", ".join(MISSES)}), plus the strict per-certificate reading of S5-P2,
below; nothing frozen moved, every output is append-only under
[`{PSD}/`]({PSD}/), and an adversarial re-derivation of all four studies
is recorded in `{PSD}/VERIFICATION2.md` (verdict: all four CONFIRMED).
**S4** (deterministic, zero LLM; `s4/s4_summary.json`) puts a 9-cluster
bootstrap CI on the paired reference-minus-arm error difference: the
governance contrast's CI [{GLO:+.3f}, {GHI:+.3f}] includes 0, so
**S4-P1 is a published MISS** (the {ZH_B}-vs-{ZH_G}-of-{N} headline gap
is real but not resolvable at 95% under 9 clusters), and one trivial
variant (`trivial_v3`) excludes 0 on the harmful side, so **S4-P2 is a
published MISS**; the per-rep elimination restatement (S4-P3) is MET.
**S5** (deterministic, zero LLM; `s5/s5_cost_sweep.json`) re-measures
warm verify cost on {len(FACTORS)} row-scale substrates of `financial`
({min(FACTORS):g}x-{max(FACTORS):g}x) plus a windows-span axis: growth
1x-to-4x is {GROWTH:.2f}x (strongly sublinear, within the pre-registered
linear bound) but one sub-noise dip breaks the strict monotonicity
clause, so **S5-P1 is a published MISS**; the verify/answer band (S5-P2)
is MET on its declared median statistic with the stricter
every-certificate reading published as a MISS alongside; the full-scan
census (S5-P3) is MET with 0 full-scan audits at every scale. The
scaled substrates themselves are deterministically rebuildable and not
shipped (`s5/SUBSTRATES.md`). S5 also carries the battery's one
**provenance correction**: the sweep script cited a
{len(PC["defect"]["corrupted_value"])}-hex-char corrupted copy of the
prereg sha in {len(PC["defect"]["fields_corrected"])} metadata fields of
its output JSON; the defect was caught by the adversarial verification,
corrected in place by `s5/fix_provenance.py` from the recomputed on-disk
hash, logged in the JSON's own `provenance_correction` block --- and it
is metadata-only: no measured number, verdict or certificate changed,
nothing was re-measured. **S6** (LLM, paid; `s6/s6_summary.json`, frozen
EN questions + sha freeze, caches `s6/runs_en/`, call log
`s6/call_log_en.jsonl`) runs the same-protocol English-question control
the battery-1 README could only concede was absent: both headline arms
move by exactly one question ({EN_B}/{N} and {EN_G}/{N} in English
against the frozen {ZH_B}/{N} and {ZH_G}/{N}), the
reference-above-governance ordering persists, and the governance arm
still errs {PR7["en_governance_errors"]}/{len(PR7["qids"])} of the
probe-only refusal questions --- all four predictions MET, and the
paper's cross-lingual threat sentence now states the measured control
instead of the concession. **S7** (LLM, paid; `s7/s7_summary.json`,
per-question ledger `s7/s7_ledger.json`, caches `s7/runs_sigma/`) has
the same backbone extract the binding request $\\sigma$ from the bare
question text and hands it to the frozen compiler: exact full-$\\sigma$
recovery on {SIG}/{N}, end-to-end error {E2E}/{N} against the
governance-informed arm's {ZH_G}/{N}, and every exactly-recovered
$\\sigma$ is end-to-end correct --- all four predictions MET; the
paper's input-modality threat sentence now carries the measurement.
Re-verification of every paper-body number the battery feeds goes
through `./reproduce_all.sh gates` (the poststudy2 sub-block re-derives
each one from these JSONs and the frozen verdict matrix).

*This subsection is generated by
[`scripts/gen_readme_poststudy2.py`](scripts/gen_readme_poststudy2.py)
from the battery-2 study JSONs;
`python3 scripts/gen_readme_poststudy2.py --check` re-asserts it
byte-for-byte.*
{END}"""


def transform(txt):
    if BEGIN in txt:
        pre, rest = txt.split(BEGIN, 1)
        if END not in rest:
            die("BEGIN marker without END marker in README.md")
        _, post = rest.split(END, 1)
        return pre + BLOCK + post
    if B1_END not in txt:
        die("cannot find the battery-1 block end marker to anchor on")
    return txt.replace(B1_END, B1_END + "\n\n" + BLOCK, 1)


def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else "--print"
    if mode == "--print":
        print(BLOCK)
        return
    cur = open(README, encoding="utf-8").read()
    new = transform(cur)
    if mode == "--write":
        if new != cur:
            open(README, "w", encoding="utf-8").write(new)
            print("README.md updated (battery-2 block)")
        else:
            print("README.md already up to date")
    elif mode == "--check":
        if new != cur:
            die("README.md is not what --write would produce "
                "(stale battery-2 block)")
        print("README poststudy2 block: OK (byte-identical to "
              "regeneration; prereg sha %s...; misses %s)"
              % (SHA[:12], ",".join(MISSES)))
    else:
        die("unknown mode %r" % mode)


if __name__ == "__main__":
    main()
