#!/usr/bin/env python3
"""Generate (and re-assert) the README's post-registration-studies block.

Numbers discipline: no result number in README.md may be hand-typed.  This
script derives every number printed in the "Post-registration studies
(2026-08-20)" subsection from the shipped study JSONs
(pilot2/poststudy_20260820/{s1/loco_report.json, s2/tsql_summary.json,
s3/s3_summary.json}), the on-disk PREREG bytes (hashed, never quoted from
memory), the shipped TR PDF (page count), and the two paper source gates
(assertion counts parsed from their own output, both required to pass).
It then splices the block between the marker comments below and rewrites
the README's "(NNN pp.)" / "NNN-assertion" mentions to the derived values.

Usage:
  python3 scripts/gen_readme_poststudy.py            # print the block
  python3 scripts/gen_readme_poststudy.py --write    # update README.md
  python3 scripts/gen_readme_poststudy.py --check    # assert README is
                                                     # exactly what --write
                                                     # would produce
"""
import hashlib
import json
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PS = os.path.join(ROOT, "pilot2", "poststudy_20260820")
README = os.path.join(ROOT, "README.md")
BEGIN = ("<!-- POSTSTUDY_BLOCK_BEGIN generated by "
         "scripts/gen_readme_poststudy.py; do not hand-edit -->")
END = "<!-- POSTSTUDY_BLOCK_END -->"


def die(msg):
    sys.stderr.write("gen_readme_poststudy: FAIL: %s\n" % msg)
    sys.exit(1)


def load(rel):
    with open(os.path.join(PS, rel), encoding="utf-8") as f:
        return json.load(f)


# ---------------------------------------------------------------- evidence
prereg_path = os.path.join(PS, "PREREG_poststudy_20260820.md")
SHA = hashlib.sha256(open(prereg_path, "rb").read()).hexdigest()
freeze = open(os.path.join(PS, "FREEZE_poststudy.sha256"),
              encoding="utf-8").read()
if SHA not in freeze:
    die("FREEZE_poststudy.sha256 does not record the on-disk PREREG sha")

S1 = load("s1/loco_report.json")
S2 = load("s2/tsql_summary.json")
S3 = load("s3/s3_summary.json")
if not (S1["prereg_sha256"] == S2["prereg"]["sha256"]
        == S3["prereg_sha256"] == SHA):
    die("a study JSON pins a different PREREG sha256")

# S1 ------------------------------------------------------------------
N = S1["n_questions"]
FOLDS = S1["loco_folds"]
N_FOLDS = len(FOLDS)
PLAIN = S1["plain_baseline_family"]
GOV = "governance_informed"
m = re.search(r">=\s*([\d.]+)", S1["predictions"]["S1-P1"]["statement"])
if not m:
    die("cannot parse the S1-P1 floor from the frozen prediction statement")
FLOOR = m.group(1)
MIN_PLAIN = min(f["error_rate"][a] for f in FOLDS.values() for a in PLAIN)
if MIN_PLAIN < float(FLOOR):
    die("a plain-baseline fold error sits below the pre-registered floor")
if not all(f["error_rate"][GOV] < min(f["error_rate"][a] for a in PLAIN)
           for f in FOLDS.values()):
    die("governance_informed is not below all plain baselines in some fold")
if any(f["error_count"]["mechanism"] != 0 for f in FOLDS.values()):
    die("mechanism errs in some fold")
S1_VERDICTS = [S1["predictions"][p].get("verdict")
               for p in ("S1-P1", "S1-P2", "S1-P3")]
if S1_VERDICTS != ["MET"] * 3:
    die("an S1 prediction verdict is not MET: %r" % (S1_VERDICTS,))
GOV_ERRORS = S1["full_sample_error_rate"][GOV] * N
if abs(GOV_ERRORS - round(GOV_ERRORS)) > 1e-9:
    die("full-sample governance error count is not integral")
GOV_ERRORS = round(GOV_ERRORS)

# S2 ------------------------------------------------------------------
W = S2["arms"]["TSQL-W"]
H = S2["arms"]["TSQL-H"]
WA = W["readings"]["null_as_error"]
WB = W["readings"]["null_as_refusal_credit"]
if not (W["answered_60_of_60_no_refusal_declaration"]
        and W["refusal_declarations"] == 0):
    die("TSQL-W refused somewhere")
if not S2["import_disjointness"].startswith("IMPORT-DISJOINTNESS OK"):
    die("S2 import-disjointness line missing")
N_NULL = len(W["bare_null_qids"])
if set(W["bare_null_qids"]) != set(W["bare_null_on_refusal_gold_qids"]):
    die("a bare NULL fell outside the refusal-gold questions")
if WB["error_count"] != WA["error_count"] - N_NULL:
    die("reading-B arithmetic broken")
if WA["error_count"] != GOV_ERRORS:
    die("TSQL-W (literal reading) is not level with the governance arm")
HA, HB = (H["readings"]["null_as_error"]["error_count"],
          H["readings"]["null_as_refusal_credit"]["error_count"])
if HA != HB:
    die("TSQL-H moves between readings")
VAL = WA["by_form"]["value"]
if WB["by_form"]["value"] != VAL:
    die("value split differs between readings")
REF_N = WA["by_form"]["refusal"]["n"]
if WA["by_form"]["refusal"]["errors"] != REF_N:
    die("literal reading: not all refusal-gold questions err")
P = S2["predictions"]
if not all(P["null_as_error"][k]["met"]
           for k in ("S2-P1", "S2-P2", "S2-P3", "S2-P4")):
    die("a reading-A S2 prediction is not met")
if P["null_as_refusal_credit"]["S2-P1"]["met"]:
    die("S2-P1 reading B is recorded met -- the published miss vanished")
if not all(P["null_as_refusal_credit"][k]["met"]
           for k in ("S2-P2", "S2-P3", "S2-P4")):
    die("an S2 reading-B prediction other than P1 missed")
MISS_W = P["null_as_refusal_credit"]["S2-P1"]["detail"]["refusal_correct_W"]
if MISS_W != "%d/%d" % (N_NULL, REF_N):
    die("reading-B refusal credit does not equal the bare-NULL count")

# S3 ------------------------------------------------------------------
REPS = S3["reps"]
K_NEW = len(REPS) - 1
BB = "baseline_claude"
bb_errs = [S3["per_arm"][BB]["per_rep"][str(r)]["errors"] for r in REPS]
gov_errs = [S3["per_arm"][GOV]["per_rep"][str(r)]["errors"] for r in REPS]
if not S3["ordering_check"]["all_reps_pass"]:
    die("S3 ordering check failed")
if not all(b > g for b, g in zip(bb_errs, gov_errs)):
    die("S3 ordering does not hold in some rep")
FLIP = {a: S3["per_arm"][a]["pooled_flip"] for a in (BB, GOV)}
for a, f in FLIP.items():
    if abs(f["flip_rate"] - f["n_flips"] / N) > 1e-12:
        die("S3 flip rate arithmetic broken for " + a)
FLIP_MAX = max(f["flip_rate"] for f in FLIP.values())
if S3["n_predictions_missed"] != 0 or not all(
        S3["predictions"][p]["pass"]
        for p in ("S3-P1", "S3-P2", "S3-P3", "S3-P4")):
    die("an S3 prediction missed")

# TR page count --------------------------------------------------------
def tr_pages():
    pdf = os.path.join(ROOT, "tr", "asof-gov-tr.pdf")
    try:
        from pypdf import PdfReader
        return len(PdfReader(pdf).pages)
    except ImportError:
        pass
    try:
        import fitz
        return fitz.open(pdf).page_count
    except ImportError:
        die("need pypdf or PyMuPDF to count TR pages")


PAGES = tr_pages()
if PAGES < 100:
    die("TR page count implausibly low: %r" % PAGES)

# gate assertion counts (both gates must PASS to be quotable) ----------
def gate_count(script, pattern):
    r = subprocess.run([sys.executable, os.path.join("tools", script)],
                       cwd=os.path.join(ROOT, "paper"),
                       capture_output=True, text=True)
    mm = re.search(pattern, r.stdout)
    if r.returncode != 0 or not mm or mm.group(2) != "0":
        die("%s did not pass cleanly (rc=%d, tail=%r)"
            % (script, r.returncode, r.stdout[-200:]))
    return int(mm.group(1))


N_CK = gate_count("check_numbers.py", r"(\d+) assertions, (\d+) failed")
N_RL = gate_count("check_redlines.py", r"(\d+) assertions, (\d+) failed")


# ---------------------------------------------------------------- block
def pct(k, n=N):
    return "%.1f%%" % (100.0 * k / n)


PSD = "pilot2/poststudy_20260820"
BLOCK = f"""{BEGIN}
### Post-registration studies (2026-08-20)

Three robustness studies answer the three most predictable review
objections --- is the n={N} headline subset-stable, how far does non-LLM
temporal-SQL machinery get without the governance axis, and is one LLM
sample per question enough. All three were pre-registered in
[`{PSD}/PREREG_poststudy_20260820.md`]({PSD}/PREREG_poststudy_20260820.md)
(sha256 `{SHA}`,
frozen before any study ran; re-asserted from the on-disk bytes by
`FREEZE_poststudy.sha256`, by every study JSON and by the number gate),
with predictions stated in advance and misses published as misses --- one
occurred, S2-P1 under its reading B, below. Nothing frozen moved:
`pilot2/runs/`, `pilot2/*.json` and `impl/certs2/` are byte-untouched;
every output is append-only under [`{PSD}/`]({PSD}/).

* **S1 --- leave-one-database-out robustness** (deterministic, zero LLM;
  evidence [`{PSD}/s1/loco_report.json`]({PSD}/s1/loco_report.json)): in
  every one of the {N_FOLDS} LOCO folds, every plain-baseline error stays
  >= {FLOOR} (minimum observed fold error {MIN_PLAIN:.3f}),
  `governance_informed` stays below all four plain baselines, and the
  compiler stays at 0 errors. All three pre-registered predictions
  (S1-P1..P3) MET.
* **S2 --- governance-blind temporal-SQL arms** (deterministic, zero LLM,
  import-disjoint from `impl/`; evidence
  [`{PSD}/s2/tsql_summary.json`]({PSD}/s2/tsql_summary.json), per-question
  ledger `s2/tsql_ledger.json`): the same-window latest-version arm
  TSQL-W answers {N}/{N} with zero refusal declarations and errs
  {WA["error_count"]}/{N} = {pct(WA["error_count"])} under the
  frozen-literal scoring --- exactly level with the governance-informed
  LLM arm's {GOV_ERRORS}/{N} --- or {WB["error_count"]}/{N} =
  {pct(WB["error_count"])} when its {N_NULL} bare `NULL`s are credited as
  implicit refusals; value questions {VAL["errors"]}/{VAL["n"]} under both
  readings; the all-history twin TSQL-H errs {HA}/{N} = {pct(HA)}.
  **Published prediction miss**: S2-P1 predicted 0/{REF_N} refusal-gold
  correct for both arms, and under the pre-declared NULL-as-implicit-
  refusal reading B the {N_NULL} bare `NULL`s score {N_NULL}/{REF_N}, so
  S2-P1 is recorded **MISSED under reading B** (MET under the
  frozen-literal reading A; both readings are computed in full in the
  JSON and both are asserted by the number gate, so neither can be
  cherry-picked).
* **S3 --- repetition study** ({K_NEW} new reps per headline arm, LLM,
  paid; evidence [`{PSD}/s3/s3_summary.json`]({PSD}/s3/s3_summary.json),
  response caches `s3/runs_rep/`, call log `s3/call_log.jsonl`): across
  {len(REPS)} reps (rep 1 := the frozen main-study run, reused not
  re-run), `baseline_claude` errs {min(bb_errs)}-{max(bb_errs)}/{N} and
  `governance_informed` {min(gov_errs)}-{max(gov_errs)}/{N}; the
  reference-above-governance ordering holds in all {len(REPS)} reps;
  pooled per-question flip rate {FLIP[BB]["n_flips"]}/{N} (reference) and
  {FLIP[GOV]["n_flips"]}/{N} (governance), i.e. <= {100 * FLIP_MAX:.1f}%
  per arm. All four predictions (S3-P1..P4) pass; 0 misses.

**Re-running.** S1 and S2 are deterministic and LLM-free (S1 needs
nothing beyond the shipped JSONs; S2 re-executes SQL, so it needs the
rebuilt warehouses). S3 needs your own LLM keys/gateway, exactly as in
"Re-running the arms" below --- and, as there, the shipped caches make
re-running unnecessary for any claim: `s3/make_s3_summary.py` re-scores
reps 2-{max(REPS)} from `s3/runs_rep/` with zero LLM calls. The study
scripts (`s1/s1_loco_analysis.py`, `s2/tsql_arms.py`, `s3/rep_harness.py`)
are shipped byte-frozen from the study tree and keep authors'-machine
path constants (the section-7 policy: frozen originals are not
re-authored for the artifact); independent re-verification of every
paper-body number they feed goes through `./reproduce_all.sh gates`,
whose poststudy block re-derives each one from the study JSONs --- the S1
fold matrix cell-by-cell from the same per-question verdict matrix the
rest of the gate already uses.

*This subsection --- and this README's page/assertion counts --- is
generated by
[`scripts/gen_readme_poststudy.py`](scripts/gen_readme_poststudy.py) from
the study JSONs; `python3 scripts/gen_readme_poststudy.py --check`
re-asserts it byte-for-byte.*
{END}"""


def transform(txt):
    # 1) machine-derived global counts
    txt = re.sub(r"\b\d+ pp\.", "%d pp." % PAGES, txt)
    txt = re.sub(r"\d+-assertion number", "%d-assertion number" % N_CK, txt)
    txt = re.sub(r"\d+-assertion red-line",
                 "%d-assertion red-line" % N_RL, txt)
    txt = re.sub(r"check_numbers\.py \(\d+ assertions\)",
                 "check_numbers.py (%d assertions)" % N_CK, txt)
    txt = re.sub(r"check_redlines\.py \(\d+\)",
                 "check_redlines.py (%d)" % N_RL, txt)
    # 2) the generated block
    if BEGIN in txt:
        pre, rest = txt.split(BEGIN, 1)
        if END not in rest:
            die("BEGIN marker without END marker in README.md")
        _, post = rest.split(END, 1)
        return pre + BLOCK + post
    anchor = "## 3. Repository layout"
    if anchor not in txt:
        die("cannot find insertion anchor %r" % anchor)
    return txt.replace(anchor, BLOCK + "\n\n" + anchor, 1)


def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else "--print"
    if mode == "--print":
        print(BLOCK)
        return
    cur = open(README, encoding="utf-8").read()
    new = transform(cur)
    if mode == "--write":
        if new != cur:
            open(README, "w", encoding="utf-8").write(new)
            print("README.md updated (block + derived counts)")
        else:
            print("README.md already up to date")
    elif mode == "--check":
        if new != cur:
            die("README.md is not what --write would produce "
                "(stale block or stale derived counts)")
        print("README poststudy block: OK (byte-identical to regeneration; "
              "prereg sha %s...; %d ck / %d rl assertions; TR %d pp.)"
              % (SHA[:12], N_CK, N_RL, PAGES))
    else:
        die("unknown mode %r" % mode)


if __name__ == "__main__":
    main()
